zfs: load keys for encrypted datasets during pool import
lxc/incus pull request #1384
Opened 2024-11-16 13:07 UTC by cyphar

If a user has set up their own zpools and given them to us to manage,
it's possible they've configured ZFS-native encryption. For the most
part, this works completely transparently to us. However, because we
manually do zpool-import and zpool-export during startup and shutdown of
Incus, ZFS datasets with keys will have their keys unloaded during
shutdown and then the keys are not automatically loaded on startup. This
results in containers being unable to start on startup because all IOs
are blocked indefinitely until the dataset keys are loaded manually by
the admin -- even if the admin has configured automatic key loading on
their system!

The simplest solution would be to pass -l to zfs-import (which causes
ZFS to auto-import all keys for all datasets in the pool). However, for
users that use keylocation=prompt, doing this naively would result in
errors when importing pools (because there is no stdin for the
zpool-import command). So we would have to silently ignore errors -- but
this would mean we would ignore regular import errors as well.

Instead, we do zfs-load-key manually after checking if there are any
non-file:// keylocation properties set within the dataset. If there are
then we are more forgiving with zfs-load-key errors and output some
warnings to tell users why their containers are not starting (previously
containers would just fail to start with no explanation). If all of the
keys are file:// then we make any load-key errors hard errors to help
admins realise their keylocation= configurations are wrong.

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

2024-11-16 13:09 UTC, cyphar commented
I haven't added tests yet because I'm not sure how you would like me to do that -- should we have just one specific test for this behaviour or run all of the ZFS-related tests on both an encrypted and unencrypted dataset?

Also let me know if you think just doing `zpool import -l` is good enough.

2024-11-18 22:34 UTC, stgraber requested changes
Logic looks good to me.

For testing, the easiest would be a system tests which only runs under INCUS_BACKEND=zfs and proceeds to manually create a test loop backed test zpool with encryption, then restarts the test Incus instance to make sure it gets unlocked properly.

2024-11-18 22:34 UTC, stgraber commented on internal/server/storage/drivers/driver_zfs.go
> +	if err := d.loadKeys(d.config["zfs.pool_name"]); err != nil {
Our coding style is to avoid the one line define+check syntax, can you split that into two separate statements?

2024-11-18 22:34 UTC, stgraber commented on internal/server/storage/drivers/driver_zfs_utils.go
> +	if _, err := subprocess.RunCommand("zfs", "load-key", "-r", dataset); err != nil {
Same here

2024-11-18 22:34 UTC, stgraber commented on internal/server/storage/drivers/driver_zfs_utils.go
> +		}).Warn(fmt.Sprintf("Dataset %q keys could not be loaded non-interactively", dataset))
Can you make that one just one line, easier to grep :)

2024-11-18 22:34 UTC, stgraber commented on internal/server/storage/drivers/driver_zfs_utils.go
> +	}
Need a line break here

2024-11-18 22:34 UTC, stgraber commented on internal/server/storage/drivers/driver_zfs_utils.go
> +		}
Need a line break here

2024-11-18 22:34 UTC, stgraber commented on internal/server/storage/drivers/driver_zfs_utils.go
> +	}
Need a line break here

2024-11-18 22:34 UTC, stgraber commented on internal/server/storage/drivers/driver_zfs_utils.go
> +	}
Need a line break here

2024-11-18 22:34 UTC, stgraber commented on internal/server/storage/drivers/driver_zfs_utils.go
> +		}
Need a line break here

2024-11-18 22:35 UTC, stgraber commented
`zpool -l` may be easier for this, assuming it behaves correctly with /dev/null as stdin so it doesn't actually end up blocking and instead fails the import.

2024-11-19 01:12 UTC, cyphar commented
@stgraber Ah, so you would prefer if the import failed? I assumed you'd prefer a warning (hence all of the logic for figuring out which datasets have non-`file://` `keylocation`s). That would make this patch much simpler. Let me test it out...

2024-11-19 02:06 UTC, stgraber commented
A storage pool failing to start should have it go into a failed state that gets retried so we should be okay with it failing to mount.

2024-11-20 12:27 UTC, cyphar commented
@stgraber Okay, `zpool import -l` will return an error if `stdin` is `/dev/null` and we have `keylocation=prompt`. However, the pool will still be imported (just without the keys loaded), so I guess we should export the pool in that case? Or should we leave it in the half-imported state?

2024-11-22 07:00 UTC, stgraber approved these changes

2024-11-22 10:11 UTC, merged