Add markdown table
lxc/incus pull request #187
Opened 2023-10-22 07:07 UTC by ShalokShalom

I hope this helps. 

Also see: https://github.com/lxc/incus/issues/186

Thanks a lot for the review

2023-10-23 17:39 UTC, ShalokShalom commented
Does anybody know, what that failure is caused by: 
https://github.com/lxc/incus/actions/runs/6602346346/job/17940899712?pr=187#step:12:18967

2023-10-23 18:28 UTC, monstermunchkin commented
> Does anybody know, what that failure is caused by: https://github.com/lxc/incus/actions/runs/6602346346/job/17940899712?pr=187#step:12:18967

That's just a random test failure. It's unrelated to your PR.

2023-10-23 18:46 UTC, ShalokShalom commented
> > Does anybody know, what that failure is caused by: https://github.com/lxc/incus/actions/runs/6602346346/job/17940899712?pr=187#step:12:18967
> 
> That's just a random test failure. It's unrelated to your PR.

Oh thanks. Does the PR look good to you?

2023-10-24 15:29 UTC, stgraber commented
```
.tmp/doc/explanation/containers_and_vms.md:7: MD009 Trailing spaces
.tmp/doc/explanation/containers_and_vms.md:10: MD009 Trailing spaces
.tmp/doc/explanation/containers_and_vms.md:12: MD009 Trailing spaces
.tmp/doc/explanation/containers_and_vms.md:13: MD009 Trailing spaces
.tmp/doc/explanation/containers_and_vms.md:15: MD009 Trailing spaces
.tmp/doc/explanation/containers_and_vms.md:16: MD009 Trailing spaces
.tmp/doc/explanation/containers_and_vms.md:17: MD009 Trailing spaces
.tmp/doc/explanation/containers_and_vms.md:18: MD009 Trailing spaces
.tmp/doc/explanation/containers_and_vms.md:19: MD009 Trailing spaces
.tmp/doc/explanation/containers_and_vms.md:25: MD009 Trailing spaces
.tmp/doc/explanation/containers_and_vms.md:36: MD009 Trailing spaces
```

2023-10-24 15:40 UTC, stgraber requested changes

2023-10-24 15:40 UTC, stgraber commented on doc/explanation/containers_and_vms.md
> +To do this, it uses the functionality provided by the kernel running on the host system.
Line break isn't needed as it's not visible in the rendered document and so just makes us needlessly diverge from the matching text in the LXD doc.

2023-10-24 15:40 UTC, stgraber commented on doc/explanation/containers_and_vms.md
> +Therefore, virtual machines can be used to run, for example, a different operating system.
The original phrasing with `, but the kernel is provided` sounds better to me.
Same comment as above about adding a line break, doesn't make a difference to the rendered document but makes it harder for us to keep up with changes in LXD.

2023-10-24 15:40 UTC, stgraber commented on doc/explanation/containers_and_vms.md
> +| Can host multiple applications         |  Can host a single app |  Can host multiple applications |
Probably should be `Can host a single application` for consistency with the other fields

2023-10-24 15:40 UTC, stgraber commented on doc/explanation/containers_and_vms.md
> +| Supported by Incus              |  Supported by Docker            |  Supported by Incus     |
Maybe go with `Supported by Docker & similar` given there are other application container runtimes/managers these days.

2023-10-24 15:40 UTC, stgraber commented on doc/explanation/containers_and_vms.md
> +Application containers like Docker package a single process or application.
I preferred the previous wording as it's technically more correct.
Docker isn't an application container, it's a tool that can create and manage (provide) application containers.

2023-10-26 07:53 UTC, closed without merging

2023-10-26 15:23 UTC, stgraber commented
Oh, why was this one closed?