Add new image requirement for cdrom drive
lxc/incus pull request #528
Opened 2024-02-23 21:49 UTC by stgraber

2024-02-23 21:52 UTC, monstermunchkin requested changes

2024-02-23 21:52 UTC, monstermunchkin commented on internal/server/instance/drivers/driver_qemu.go
> +			return fmt.Errorf("This virtual machine image requires an agent cdrom drive be added.")
```suggestion
			return fmt.Errorf("This virtual machine image requires an agent cdrom drive be added")
```

2024-02-23 21:54 UTC, stgraber commented on internal/server/instance/drivers/driver_qemu.go
> +			return fmt.Errorf("This virtual machine image requires an agent cdrom drive be added.")
Thanks!

2024-02-23 21:57 UTC, monstermunchkin approved these changes

2024-02-24 02:28 UTC, hallyn approved these changes

2024-02-24 02:28 UTC, merged