Migration stateful feature added (WIP) have not tested yet
lxc/incus pull request #781
Opened 2024-04-23 03:59 UTC by Abhiram824

2024-04-23 13:01 UTC, stgraber commented
API extensions should always be appended to the existing list, not added at the top or middle of the files.

2024-04-23 13:07 UTC, stgraber requested changes

2024-04-23 13:07 UTC, stgraber commented on internal/instance/config.go
> -	// Caller is responsible for full validation of any raw.* value.
That line shouldn't have been removed as it's related to the next entry.

2024-04-23 13:07 UTC, stgraber commented on internal/server/instance/drivers/driver_lxc.go
> +	if stateful && util.IsFalse(d.localConfig["migration.stateful"]){
Should be checking expandedConfig instead of localConfig

2024-04-23 13:07 UTC, stgraber commented on internal/server/instance/drivers/driver_lxc.go
> +		return fmt.Errorf("This instance requires migration.stateful to be true. Please set migration.stateful=true on the instance")
I'd probably rephrase it more like: 

Stateful start requires that the instance migration.stateful set to true

2024-04-23 13:07 UTC, stgraber commented on internal/server/instance/drivers/driver_lxc.go
> +	if stateful && util.IsFalse(d.localConfig["migration.stateful"]){
Should also be expandedConfig

2024-04-23 13:07 UTC, stgraber commented on internal/server/instance/drivers/driver_lxc.go
> +		return fmt.Errorf("This instance requires migration.stateful to be true. Please set migration.stateful=true on the instance")
Stateful stop requires the instance to have migration.stateful set to true

2024-04-23 13:07 UTC, stgraber commented on internal/server/instance/drivers/driver_lxc.go
> +
One more line break then needed here

2024-04-23 13:07 UTC, stgraber commented on internal/server/instance/drivers/driver_lxc.go
> +	if stateful && util.IsFalse(d.localConfig["migration.stateful"]){
expandedConfig here too

2024-04-23 13:07 UTC, stgraber commented on internal/server/instance/drivers/driver_lxc.go
> +		return fmt.Errorf("This instance requires migration.stateful to be true. Please set migration.stateful=true on the instance")
Stateful snapshots require that the instance has migration.stateful set to true

2024-04-23 13:08 UTC, stgraber commented
I left a few more comments in line. General structure looks good so it's just about fixing a bunch of small things. 

Also make sure to run both `gofmt -s -w ./` and `make static-analysis` to fix some formatting issues and then make sure that there's nothing else that needs fixing.

2024-04-24 00:06 UTC, Abhiram824 commented
> I left a few more comments in line. General structure looks good so it's just about fixing a bunch of small things.
> 
> Also make sure to run both `gofmt -s -w ./` and `make static-analysis` to fix some formatting issues and then make sure that there's nothing else that needs fixing.

I ran both commands. make static-analysis was able to run for everything except for rest-api-up-to-date, but since there were no changes to doc/rest-api.yaml I just moved on for now

2024-04-24 22:08 UTC, stgraber commented
> I ran both commands. make static-analysis was able to run for everything except for rest-api-up-to-date, but since there were no changes to doc/rest-api.yaml I just moved on for now

It's telling you that there should be a change to `doc/rest-api.yaml`.

Run `make update-api`, that will generate the applicable change to `doc/rest-api.yaml`, then add that in a new commit title: `doc/rest-api: Refresh swagger YAML`

2024-04-25 06:09 UTC, stgraber commented
Looking into that one now.

2024-04-25 06:16 UTC, stgraber commented
Changes I made:
 - Rebased on current main branch
 - Moved changes to generated files into their own commit
 - Rebased the fix commits into the main commits
 - Slightly reworded the error messages
 - Added bug reference to commit

Now just waiting to see if Github Actions catch anything else :)

2024-04-25 06:32 UTC, stgraber commented
Also had to move the API extension to the bottom of the file.

2024-04-25 06:34 UTC, stgraber approved these changes

2024-04-25 07:32 UTC, merged